In [2]:
import os

In [3]:
os.getcwd()

'C:\\Users\\Daniel'

In [4]:
os.chdir("E:\python")

In [5]:
os.getcwd()

'E:\\python'

In [6]:
import numpy as np;
import pandas as pd;
import matplotlib.pyplot as plt

In [7]:
df=pd.read_csv('x_train.csv') # read the train data from the file

In [8]:
df.describe()

GeneId       H3K4me3       H3K4me1      H3K36me3       H3K9me3  \
count  1.548500e+06  1.548500e+06  1.548500e+06  1.548500e+06  1.548500e+06   
mean   7.743000e+03  1.628247e+00  1.533522e+00  3.368313e+00  5.099660e+00   
std    4.470136e+03  2.117349e+00  1.819352e+00  4.683728e+00  1.233961e+01   
min    1.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    3.872000e+03  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
50%    7.743000e+03  1.000000e+00  1.000000e+00  2.000000e+00  1.000000e+00   
75%    1.161400e+04  2.000000e+00  2.000000e+00  4.000000e+00  3.000000e+00   
max    1.548500e+04  1.630000e+02  9.300000e+01  1.060000e+02  1.610000e+02   

           H3K27me3  
count  1.548500e+06  
mean   1.118989e+00  
std    1.402116e+00  
min    0.000000e+00  
25%    0.000000e+00  
50%    1.000000e+00  
75%    2.000000e+00  
max    1.700000e+02

In [9]:
df.isnull().values.sum() #count the numbers of missing value in the data

0

In [10]:
data=df.iloc[:,1:6] # get rid of the GeneId column

In [11]:
data

H3K4me3  H3K4me1  H3K36me3  H3K9me3  H3K27me3
0              2        1         4        1         0
1              0        2         1        1         1
2              0        0         4        1         1
3              0        2         2        0         1
4              2        0         0        0         0
5              1        2         0        0         1
6              2        2         2        0         1
7              1        1         4        2         2
8              2        3         4        3         1
9              0        2         3        2         2
10             2        0         3        4         2
11             0        0         4        1         2
12             2        0         5        3         2
13             1        0         3        9         2
14             1        1         0        8         2
15             0        0         1       14         1
16             2        0         2       15         1
17             1        1         2       12         0
18             1        1         3       12         1
19             1        1         2        7         0
20             3        0         3        4         4
21             1        1         4        5         1
22             1        0         3        5         0
23             1        0         1        2         1
24             2        0         1        3         0
25             1        0         4        2         0
26             3        0         7        4         1
27             2        3         3        4         1
28             3        1         4        4         1
29             3        0         3        1         1
...          ...      ...       ...      ...       ...
1548470        0        1         0        2         0
1548471        3        1         0        3         1
1548472        3        0         1        2         1
1548473        4        0         1        1         0
1548474        2        0         3        1         0
1548475        4        0         3        1         0
1548476        4        0         0        1         0
1548477        3        0         1        1         0
1548478        1        1         0        3         1
1548479        2        1         0        1         0
1548480        3        2         0        0         1
1548481        1        3         3        0         2
1548482        2        1         0        0         0
1548483        2        1         0        0         1
1548484        0        1         0        0         3
1548485        0        0         0        2         3
1548486        0        0         0        0         0
1548487        0        0         0        0         0
1548488        0        0         0        0         0
1548489        0        0         0        0         0
1548490        0        0         0        0         0
1548491        0        0         0        0         0
1548492        0        0         0        0         0
1548493        0        0         0        0         0
1548494        0        0         0        0         1
1548495        0        1         0        0         1
1548496        1        1         0        1         1
1548497        2        0         0        0         1
1548498        0        0         0        3         1
1548499        0        0         0        2         1

[1548500 rows x 5 columns]

In [12]:
mydata=data.values   #convert the data frame to numpy array
mydata=mydata.flatten() #convert the n-dimension array to one-dimension array

In [13]:
mydata=np.reshape(mydata,(15485,500)) #reshape the array so that there are 500 columns each row

In [14]:
mydata

array([[2, 1, 4, ..., 0, 0, 1],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 6, 3, ..., 4, 3, 0],
       ..., 
       [0, 2, 1, ..., 2, 0, 1],
       [0, 0, 0, ..., 2, 0, 0],
       [2, 0, 0, ..., 0, 2, 1]], dtype=int64)

In [15]:
from sklearn import preprocessing

In [16]:
robust_scaler=preprocessing.RobustScaler()

In [17]:
x_train=robust_scaler.fit_transform(mydata)

In [18]:
x_train

array([[ 0.5       ,  0.        ,  1.        , ..., -0.33333333,
        -0.5       ,  0.        ],
       [ 0.        , -0.5       ,  0.        , ..., -0.33333333,
        -0.5       , -0.5       ],
       [ 0.        ,  2.5       ,  0.66666667, ...,  1.        ,
         1.        , -0.5       ],
       ..., 
       [-0.5       ,  0.5       ,  0.        , ...,  0.33333333,
        -0.5       ,  0.        ],
       [-0.5       , -0.5       , -0.33333333, ...,  0.33333333,
        -0.5       , -0.5       ],
       [ 0.5       , -0.5       , -0.33333333, ..., -0.33333333,
         0.5       ,  0.        ]])

In [19]:
pd.DataFrame(x_train)

0    1         2     3    4    5    6         7    8    9   ...   490  \
0      0.5  0.0  1.000000   0.0 -0.5 -0.5  0.5  0.000000  0.0  0.0 ...   0.5   
1      0.0 -0.5  0.000000  -0.5 -0.5 -0.5 -0.5 -0.333333 -0.5 -0.5 ...   2.0   
2      0.0  2.5  0.666667   0.0  0.0  0.0  2.5  0.000000  0.5  0.5 ...   0.0   
3     -0.5  1.5  0.666667   0.5  0.0 -0.5  0.5  2.333333  0.0  1.0 ...   1.5   
4     -0.5  0.0  0.333333  -0.5 -0.5 -0.5 -0.5  1.000000 -0.5 -0.5 ...  -0.5   
5      0.0 -0.5 -0.333333  -0.5 -0.5  1.5  0.0  0.333333  0.0  0.0 ...   0.5   
6      0.0  0.0  0.000000   1.0  0.5  0.0  0.5  0.333333  0.5  0.0 ...  -0.5   
7      0.0  0.5  2.000000  -0.5  0.5  0.0  0.5  3.666667  0.5  0.0 ...   0.0   
8      0.5  1.0  1.000000   0.0  1.0  1.5 -0.5  1.666667  0.0 -0.5 ...   0.5   
9     -0.5  2.0  0.333333   0.0 -0.5 -0.5  0.5  0.000000  0.0  0.0 ...  -0.5   
10    -0.5  0.0  0.666667   0.0  0.0 -0.5 -0.5  0.333333  0.0  1.0 ...   1.0   
11     0.0  3.5  0.333333   2.0  0.0  0.0  3.0  0.000000  2.5  0.0 ...   0.0   
12     0.5  0.0 -0.333333   0.0 -0.5 -0.5  0.5 -0.333333  0.0 -0.5 ...  -0.5   
13     0.5  3.0  0.666667   1.5  0.0  0.5  3.5 -0.333333  3.0  0.0 ...   0.0   
14     0.0  0.0 -0.333333   0.0  0.0  0.0  0.0  0.333333  0.0  0.5 ...  -0.5   
15     0.0 -0.5 -0.333333  -0.5 -0.5  0.0 -0.5 -0.333333 -0.5 -0.5 ...  -0.5   
16     0.0 -0.5  0.000000   0.5  0.5 -0.5 -0.5 -0.333333 -0.5 -0.5 ...  -0.5   
17     1.5  0.0  0.666667   1.0  0.0  1.0  0.0  0.333333  0.5  0.5 ...   0.5   
18     3.0  0.0 -0.333333   0.0  0.0  2.0  0.5  0.000000 -0.5 -0.5 ...   2.0   
19     1.0  0.5 -0.333333   1.0  0.5  2.0  1.0  0.000000  1.0 -0.5 ...  -0.5   
20    -0.5  0.0  0.333333   1.5  1.0 -0.5  0.5  0.333333  1.0  1.0 ...   0.0   
21     2.5  0.5 -0.333333   0.5  0.5  2.5  0.0 -0.333333  1.5  1.0 ...   2.0   
22    -0.5  0.5 -0.333333  -0.5  0.0 -0.5  0.5 -0.333333 -0.5 -0.5 ...   0.0   
23     0.0 -0.5 -0.333333   0.0  0.0  0.5  0.0 -0.333333 -0.5  0.5 ...   0.5   
24     0.0  0.0  0.000000   0.0 -0.5  0.0  0.0  0.333333  0.0 -0.5 ...   0.5   
25     0.0  0.5  0.000000   0.0  0.0  1.0  0.5 -0.333333  0.0 -0.5 ...   0.5   
26     0.0  0.0 -0.333333   0.5  0.0  0.0  0.0  0.333333  0.0  0.0 ...   1.0   
27    -0.5  1.0  0.000000   1.5  1.5 -0.5  0.5  0.333333  1.5  1.5 ...   0.0   
28    -0.5 -0.5  0.666667   1.0  0.5 -0.5  1.0  0.333333  1.0 -0.5 ...  -0.5   
29    -0.5  0.5 -0.333333   0.5  0.0  0.0 -0.5 -0.333333 -0.5 -0.5 ...   0.0   
...    ...  ...       ...   ...  ...  ...  ...       ...  ...  ... ...   ...   
15455  1.5 -0.5  0.000000   1.0  1.0  0.5 -0.5 -0.333333  0.0  0.0 ...   0.5   
15456 -0.5  0.0 -0.333333   0.0  0.0 -0.5  0.0  0.666667  1.0  0.0 ...   0.0   
15457 -0.5 -0.5 -0.333333   0.0  0.0 -0.5 -0.5 -0.333333 -0.5 -0.5 ...   0.0   
15458 -0.5  2.5  4.000000   2.0  0.0 -0.5  1.0  3.666667  1.0  0.5 ...   0.0   
15459 -0.5 -0.5 -0.333333  -0.5 -0.5 -0.5 -0.5 -0.333333 -0.5 -0.5 ...  -0.5   
15460  2.0 -0.5  0.333333   1.0  1.5  1.0  0.0  0.333333  0.5  1.5 ...   2.5   
15461 -0.5  1.5  0.000000   0.5 -0.5  0.0  1.0 -0.333333  0.0  0.5 ...   0.0   
15462  0.0  0.5  0.000000   0.5 -0.5 -0.5  0.0 -0.333333 -0.5 -0.5 ...   0.5   
15463 -0.5  0.5  1.000000  -0.5 -0.5 -0.5  0.5  0.666667 -0.5  0.0 ...   0.5   
15464 -0.5 -0.5 -0.333333  -0.5 -0.5 -0.5  0.5 -0.333333  0.0  1.5 ...   1.0   
15465 -0.5 -0.5  0.333333  -0.5 -0.5 -0.5 -0.5 -0.333333 -0.5 -0.5 ...  -0.5   
15466  0.5  0.5  4.000000  12.0  1.0  0.0  2.0  4.666667  4.0  0.5 ...  -0.5   
15467  0.5  0.0 -0.333333   1.0  0.0 -0.5  0.5 -0.333333  0.0  0.5 ...  -0.5   
15468 -0.5  1.5  0.666667  -0.5  0.0 -0.5  0.5  0.666667 -0.5  0.0 ...  -0.5   
15469 -0.5  0.0  0.333333  -0.5  0.0  2.0  0.0  0.333333  0.0  0.0 ...   0.0   
15470 -0.5 -0.5 -0.333333  -0.5 -0.5 -0.5 -0.5 -0.333333 -0.5 -0.5 ...  -0.5   
15471  0.0  0.5  0.000000  -0.5  0.0  1.0 -0.5  0.333333 -0.5  0.0 ...   1.5   
15472  0.5  0.0  0.000000   1.5  0.0  0.5  0.0  0.333333  0.0  0.5 ...  -0.5   
15473  

In [20]:
df=pd.read_csv('x_test.csv')

In [21]:
df

GeneId  H3K4me3  H3K4me1  H3K36me3  H3K9me3  H3K27me3
0            1        2        3         4        3         4
1            1        0        0         4        3         2
2            1        2        1         4        1         1
3            1        1        0         2        0         6
4            1        1        0         3        0         5
5            1        0        3         1        0         3
6            1        1        1         5        0         1
7            1        1        2         7        2         2
8            1        1        0         7        4         3
9            1        0        0         3        0         3
10           1        0        0         0        0         0
11           1        0        1         1        0         0
12           1        1        2         5        2         2
13           1        2        0         7        1         3
14           1        0        0         4        0         2
15           1        1        1         9        2         2
16           1        1        2        12        4         4
17           1        1        1         4        6         3
18           1        0        0         1        0         0
19           1        1        1         8        3         1
20           1        1        0         7        4         3
21           1        0        0         0        0         0
22           1        0        0         7        3         2
23           1        0        1        15        2         2
24           1        0        1         8        3         4
25           1        1        3         1        0         2
26           1        2        3         3        0         1
27           1        2        1         7        2         4
28           1        2        1         5        1         3
29           1        0        1         2        0         0
...        ...      ...      ...       ...      ...       ...
387070    3871        0        0         1        0         0
387071    3871        0        0         1        0         0
387072    3871        0        0         1        0         0
387073    3871        1        1         1        1         0
387074    3871        1        1         0        0         0
387075    3871        0        3         0        0         1
387076    3871        0        2         0        0         1
387077    3871        0        0         0        0         0
387078    3871        0        0         0        0         0
387079    3871        1        0         1        1         1
387080    3871        0        1         2        1         2
387081    3871        0        0         0        0         0
387082    3871        0        0         0        0         0
387083    3871        0        1         1        0         0
387084    3871        0        0         1        1         0
387085    3871        0        0         0        1         0
387086    3871        0        1         0        0         1
387087    3871        1        1         1        3         1
387088    3871        1        1         2        2         0
387089    3871        0        0         0        0         1
387090    3871        1        2         0        1         1
387091    3871        0        1         0        0         0
387092    3871        0        0         0        0         0
387093    3871        0        0         0        0         1
387094    3871        0        0         0        0         0
387095    3871        0        0         0        0         0
387096    3871        0        0         0        0         2
387097    3871        1        1         1        0         1
387098    3871        2        1         2        0         1
387099    3871        0        0         0        0         0

[387100 rows x 6 columns]

In [22]:
df=df.iloc[:,1:6]

In [23]:
df=df.values

In [24]:
df=df.reshape(3871,500)

In [25]:
df


array([[ 2,  3,  4, ...,  6,  2,  3],
       [ 1,  4,  2, ...,  3,  3,  1],
       [ 0,  6,  4, ...,  7,  1,  2],
       ..., 
       [ 2,  3, 13, ...,  3,  0,  0],
       [ 1,  2,  1, ...,  1,  0,  2],
       [ 1,  4,  4, ...,  0,  0,  0]], dtype=int64)

In [26]:
x_test=robust_scaler.transform(df)

In [27]:
pd.DataFrame(x_test)

0    1         2     3    4    5    6         7     8    9   ...   490  \
0     0.5  1.0  1.000000   1.0  1.5 -0.5 -0.5  1.000000   1.0  0.5 ...   0.0   
1     0.0  1.5  0.333333   1.0  0.0 -0.5  0.5 -0.333333   1.0  0.5 ...   0.5   
2    -0.5  2.5  1.000000   0.5  1.0  0.0  2.0  0.666667   0.0  0.5 ...   0.5   
3     0.0 -0.5 -0.333333   1.0 -0.5 -0.5 -0.5 -0.333333  -0.5 -0.5 ...   0.0   
4     0.0 -0.5  0.000000  -0.5  0.0 -0.5 -0.5 -0.333333  -0.5 -0.5 ...   0.0   
5    -0.5  0.0  0.000000   0.0  0.5  0.0  0.5  0.000000   0.0  1.0 ...   0.0   
6    -0.5 -0.5  0.000000   0.0  0.5  1.0  0.5 -0.333333  -0.5 -0.5 ...   1.5   
7    -0.5 -0.5 -0.333333  -0.5 -0.5 -0.5 -0.5 -0.333333  -0.5 -0.5 ...   3.0   
8    -0.5  0.5  0.666667   0.0 -0.5 -0.5  0.5  0.333333   0.5 -0.5 ...  -0.5   
9    -0.5  0.0 -0.333333  -0.5 -0.5 -0.5  0.0  0.000000  -0.5 -0.5 ...   0.5   
10   -0.5 -0.5 -0.333333  -0.5  0.0 -0.5 -0.5 -0.333333   0.0  0.0 ...  -0.5   
11    0.0  2.5  0.666667   0.5 -0.5  0.0  2.5  0.000000  -0.5 -0.5 ...   0.0   
12    0.5  0.0 -0.333333   0.5  0.5  1.0  0.0 -0.333333   0.5 -0.5 ...  -0.5   
13   -0.5  0.0 -0.333333  -0.5  0.5  0.0 -0.5  0.000000  -0.5  0.0 ...  -0.5   
14    0.0  1.0  2.666667   0.5  0.5  0.0 -0.5  1.000000   0.5  0.0 ...   0.0   
15    0.0  0.5  2.333333   1.0 -0.5 -0.5 -0.5  0.333333   0.0 -0.5 ...  -0.5   
16    0.0  0.0  3.000000   0.5  1.5  0.0 -0.5  1.000000  -0.5  0.0 ...  -0.5   
17    0.5  3.0  1.333333   1.0  0.0 -0.5  0.5  2.333333   0.0  0.0 ...   1.0   
18    0.5 -0.5  0.333333  -0.5  0.0  0.0  0.5  1.666667  -0.5  0.0 ...   0.5   
19   -0.5  0.0  1.000000  -0.5  0.0 -0.5  0.0  0.666667   0.0 -0.5 ...   0.0   
20   -0.5  0.0  1.000000   0.0  0.0  0.0 -0.5  1.333333  -0.5 -0.5 ...   0.5   
21    0.0  0.5  0.000000   1.0 -0.5  0.5 -0.5  0.333333   1.0 -0.5 ...  -0.5   
22    0.5  1.5 -0.333333   0.5 -0.5  0.0  2.0 -0.333333   0.0 -0.5 ...  -0.5   
23   -0.5 -0.5 -0.333333  -0.5 -0.5 -0.5 -0.5 -0.333333  -0.5 -0.5 ...   0.0   
24    0.0  0.5  0.000000   0.0  0.0  0.0  0.5  0.000000   0.0  0.0 ...   0.5   
25   -0.5  1.0  6.000000   6.5 -0.5  0.5  0.5  5.000000   4.5  0.5 ...   0.0   
26   -0.5 -0.5 -0.333333  -0.5  0.0  0.5 -0.5 -0.333333  -0.5 -0.5 ...   3.0   
27    1.5  1.0  0.000000   0.0 -0.5  0.5  4.5  0.000000   1.0 -0.5 ...   0.0   
28    0.5  0.0  0.000000   0.5 -0.5  0.5  0.0 -0.333333   0.0 -0.5 ...  -0.5   
29    0.0  1.0  0.000000   0.0 -0.5  0.5  2.0 -0.333333   0.5 -0.5 ...  -0.5   
...   ...  ...       ...   ...  ...  ...  ...       ...   ...  ... ...   ...   
3841 -0.5 -0.5  0.000000  -0.5 -0.5 -0.5 -0.5 -0.333333  -0.5 -0.5 ...   0.0   
3842  0.0  0.0  0.666667  -0.5  1.5  0.5 -0.5  0.000000   0.0  0.0 ...   2.5   
3843  0.5  3.5  2.000000   0.5  0.5 -0.5  3.5  3.333333   1.5  0.5 ...   0.5   
3844  0.0  0.0  0.333333   0.5  0.5  0.0  0.5  0.666667   0.0 -0.5 ...   0.0   
3845 -0.5 -0.5 -0.333333  -0.5 -0.5  0.5 -0.5 -0.333333  -0.5  0.5 ...   0.0   
3846 -0.5  0.0  0.000000  -0.5  0.0 -0.5  0.5 -0.333333  -0.5  1.5 ...   0.0   
3847 -0.5 -0.5 -0.333333  -0.5 -0.5 -0.5 -0.5 -0.333333  -0.5 -0.5 ...  -0.5   
3848  0.5  1.0  0.666667   1.0  1.0  1.0  1.0 -0.333333   0.5  1.0 ...   2.0   
3849 -0.5  1.0 -0.333333   1.0 -0.5  0.0  0.5 -0.333333   1.0  0.5 ...  -0.5   
3850  0.0  2.0  2.666667  24.5  0.5  0.5  2.5  2.666667  31.0 -0.5 ...   0.5   
3851  1.0  1.0  0.000000  -0.5  0.0  1.5  1.0 -0.333333   0.0  0.5 ...   0.5   
3852  1.5  1.0  0.666667   0.0 -0.5  0.5  0.5 -0.333333   1.0  0.0 ...   0.0   
3853  0.0  1.5  0.666667  -0.5  0.0  0.5  0.5 -0.333333   1.0  1.0 ...   1.0   
3854  1.0 -0.5 -0.333333   0.0  0.0  1.5 -0.5 -0.333333  -0.5 -0.5 ...  -0.5   
3855 -0.5  0.5  0.000000  -0.5  0.0 -0.5  0.0  0.000000   0.0  0.5 ...  -0.5   
3856 -0.5  0.5  1.000000   0.5  0.0 -0.5  0.0 -0.333333  -0.5  0.0 ...  -0.5   
3857  2.0  0.0 -0.333333   0.5  0.0  1.0  0.0  0.000000   0.5 -0.5 ...  -0.5   
3858 -0.5  0.5 -0.333333   0.5 -0.5 -0.5  0.0  1.000000   0.0  0.0 ...  -0.5   
3859 -

In [28]:
df=pd.read_csv('y_train.csv')

In [29]:
df

GeneId  Prediction
0           1           0
1           2           0
2           3           1
3           4           1
4           5           1
5           6           0
6           7           1
7           8           0
8           9           1
9          10           1
10         11           1
11         12           1
12         13           1
13         14           1
14         15           1
15         16           1
16         17           1
17         18           0
18         19           0
19         20           1
20         21           1
21         22           0
22         23           1
23         24           0
24         25           0
25         26           0
26         27           1
27         28           1
28         29           1
29         30           1
...       ...         ...
15455   15456           1
15456   15457           0
15457   15458           0
15458   15459           0
15459   15460           0
15460   15461           0
15461   15462           0
15462   15463           0
15463   15464           1
15464   15465           0
15465   15466           1
15466   15467           1
15467   15468           0
15468   15469           1
15469   15470           0
15470   15471           0
15471   15472           0
15472   15473           0
15473   15474           0
15474   15475           0
15475   15476           0
15476   15477           0
15477   15478           0
15478   15479           0
15479   15480           1
15480   15481           0
15481   15482           0
15482   15483           0
15483   15484           0
15484   15485           0

[15485 rows x 2 columns]

In [30]:
df=df.iloc[:,1:2]

In [31]:
df

Prediction
0               0
1               0
2               1
3               1
4               1
5               0
6               1
7               0
8               1
9               1
10              1
11              1
12              1
13              1
14              1
15              1
16              1
17              0
18              0
19              1
20              1
21              0
22              1
23              0
24              0
25              0
26              1
27              1
28              1
29              1
...           ...
15455           1
15456           0
15457           0
15458           0
15459           0
15460           0
15461           0
15462           0
15463           1
15464           0
15465           1
15466           1
15467           0
15468           1
15469           0
15470           0
15471           0
15472           0
15473           0
15474           0
15475           0
15476           0
15477           0
15478           0
15479           1
15480           0
15481           0
15482           0
15483           0
15484           0

[15485 rows x 1 columns]

In [32]:
y_train=df.values

In [33]:
y_train=y_train.flatten()

In [34]:
y_train

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [35]:
from sklearn.ensemble import RandomForestClassifier

In [36]:
from sklearn.model_selection import cross_val_score

In [37]:
from sklearn import svm

In [38]:
clf = RandomForestClassifier(random_state=0)

In [39]:
scores = cross_val_score(clf, x_train, y_train, cv=5, scoring='roc_auc') # using preprocessed data

In [40]:
scores

array([ 0.90143336,  0.89711852,  0.89714519,  0.89330529,  0.88141193])

In [41]:
scores = cross_val_score(clf, mydata, y_train, cv=5, scoring='roc_auc') # using raw data

In [42]:
scores

array([ 0.90148317,  0.89720479,  0.89711036,  0.89345302,  0.88132283])

In [43]:
from sklearn import linear_model

In [44]:
logreg = linear_model.LogisticRegression()

In [45]:
scores = cross_val_score(logreg,x_train,y_train,cv=10)

In [46]:
scores

array([ 0.87088444,  0.84118786,  0.85087153,  0.8431246 ,  0.85022595,
        0.8431246 ,  0.83925113,  0.85529716,  0.81383323,  0.83193277])

In [47]:
from sklearn.neural_network import MLPClassifier

In [48]:
clf = MLPClassifier(alpha=1e-5, hidden_layer_sizes=(100, 2), random_state=1)

In [49]:
scores = cross_val_score(clf,x_train,y_train,cv=5)

In [50]:
scores

array([ 0.85248547,  0.84796643,  0.84662577,  0.84011628,  0.8123385 ])

In [51]:
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import StratifiedKFold

In [61]:
cv = StratifiedKFold(n_splits=6)
classifier1 = linear_model.LogisticRegression()
classifier2 = svm.SVC(kernel='linear', probability=True, random_state=1)
classifier3 = RandomForestClassifier(random_state=1)
classifier4 = MLPClassifier(alpha=1e-5, hidden_layer_sizes=(30, 2), random_state=1)

In [62]:
aucs = []

In [63]:
for train, test in cv.split(x_train, y_train):
    probas_ = classifier4.fit(x_train[train], y_train[train]).predict_proba(x_train[test])
    # Compute ROC curve and area the curve
    fpr, tpr, thresholds = roc_curve(y_train[test], probas_[:, 1])
    roc_auc = auc(fpr, tpr)
    aucs.append(roc_auc)

In [64]:
aucs

[0.90172837015367024,
 0.89252178476555566,
 0.89572675130780666,
 0.86954209959985207,
 0.89231672695306308,
 0.86299888948714498]